# Generated by Django 4.0 on 2023-07-30 23:51

from django.db import migrations, models
from django.utils import timezone



def create_data(apps, schema_editor):
    Form = apps.get_model('form', 'Form')
    Form(name="Marvin", agreement=True, current_date=timezone.now(), current_time=timezone.now()).save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Full Name: ')),
                ('agreement', models.BooleanField(default=False, verbose_name='Agreed')),
            ],
        ),
    ]
