# Generated by Django 4.0 on 2023-07-31 00:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='current_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='form',
            name='current_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Time'),
        ),
    ]
