# Generated by Django 4.0 on 2023-08-01 19:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_current_date_form_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='current_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Session Date'),
        ),
        migrations.AlterField(
            model_name='form',
            name='current_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Session Time'),
        ),
    ]
