# Generated by Django 4.0 on 2023-08-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_alter_form_current_date_alter_form_current_time'),
    ]

    operations = [
    ]
